version: '3.8'
services:
  mongodb:
    image: 'mongo'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=max
      - MONGO_INITDB_ROOT_PASSWORD=secret
  backend:
    image: 'backend'
    environment:
      - MONGODB_USERNAME=max
      - MONGODB_PASSWORD=secret
      - MONGODB_URL=mongodb
    ports:
      - '8080:80'
    depends_on:
      - mongodb

volumes:
  data:
